// Benchmark System — the universal source of truth for competitive benchmarking,
// reverse engineering, forensic auditing, and autonomous gap-filling.
// Research conducted 2026-10-02 across Lovable, Bolt.new, V0 by Vercel, Replit,
// Cursor, Layout.dev, and the broader AI app builder market.

export const BENCHMARK_VERSION = "1.0.0";
export const RESEARCH_DATE = "2026-10-02";

// ─── TOP 3 SIMILAR SYSTEMS (researched & rated) ─────────────────────────────
export const TOP_SYSTEMS = [
  {
    rank: 1,
    name: "Lovable",
    url: "lovable.dev",
    rating: 4.8,
    best_for: "Non-technical founders building full applications",
    key_strength: "Full-stack generation with native backend, auth, and deployment",
    pricing: "Free $0 / Pro $25/mo / Business $50/mo",
    full_stack: true,
    visual_edits: true,
    agent_mode: true,
    supabase_native: true,
    stripe_native: true,
    github_sync: true,
    one_click_deploy: true,
    templates: true,
    credit_billing: true,
    selected_as_benchmark: true,
  },
  {
    rank: 2,
    name: "Bolt.new",
    url: "bolt.new",
    rating: 4.5,
    best_for: "Teams demoing ideas quickly",
    key_strength: "Speed to a shareable prototype with growing backend features",
    pricing: "Free + paid $25/mo",
    full_stack: true,
    visual_edits: false,
    agent_mode: true,
    supabase_native: false,
    stripe_native: false,
    github_sync: true,
    one_click_deploy: true,
    templates: false,
    credit_billing: true,
    selected_as_benchmark: false,
  },
  {
    rank: 3,
    name: "V0 by Vercel",
    url: "v0.app",
    rating: 4.3,
    best_for: "Product teams handing off to engineers",
    key_strength: "Production-quality React/Next.js code with security scanning",
    pricing: "Free ~$5/mo / Premium ~$20/mo / Team ~$30/user/mo",
    full_stack: false,
    visual_edits: false,
    agent_mode: false,
    supabase_native: false,
    stripe_native: false,
    github_sync: true,
    one_click_deploy: true,
    templates: false,
    credit_billing: true,
    selected_as_benchmark: false,
  },
];

export const BENCHMARK = TOP_SYSTEMS.find((s) => s.selected_as_benchmark);

// ─── REVERSE-ENGINEERED TECHNOLOGY STACK (Lovable) ──────────────────────────
export const REVERSE_ENGINEERED_STACK = [
  {
    layer: "Frontend",
    technologies: ["React 18", "Tailwind CSS", "shadcn/ui", "TypeScript", "Vite"],
    capability: "Component-driven UI generation with production-grade React/Next.js output",
    reverse_engineered: true,
    smai_equivalent: "React + Tailwind + shadcn/ui (✅ already matched)",
  },
  {
    layer: "Backend / Database",
    technologies: ["Supabase (PostgreSQL)", "Row Level Security", "Realtime subscriptions", "Storage"],
    capability: "Native backend provisioning — database, auth, and storage auto-connected to generated apps",
    reverse_engineered: true,
    smai_equivalent: "Base44 entities + Supabase connector (partial — no auto-provision for generated apps)",
  },
  {
    layer: "Authentication",
    technologies: ["Supabase Auth", "Email/password", "Google OAuth", "Magic links"],
    capability: "Full auth system generated from a plain-English description",
    reverse_engineered: true,
    smai_equivalent: "Base44 Auth (✅ matched — email, Google, OTP, reset)",
  },
  {
    layer: "Payments",
    technologies: ["Stripe", "Checkout flows", "Webhook handling", "Database tables auto-generated"],
    capability: "Native Stripe integration — describe pricing, get checkout + webhooks + tables",
    reverse_engineered: true,
    smai_equivalent: "MonetizationProfile entity exists but NO live Stripe integration",
  },
  {
    layer: "Code Ownership",
    technologies: ["GitHub sync", "Full codebase export", "No lock-in"],
    capability: "Entire codebase syncs to GitHub so developers can take over",
    reverse_engineered: true,
    smai_equivalent: "GitHub connector exists but NO auto-sync of generated code to repos",
  },
  {
    layer: "AI Agent Mode",
    technologies: ["Autonomous codebase exploration", "Proactive debugging", "Real-time web search", "Multi-file changes"],
    capability: "Agent Mode takes ownership of a task — explores, debugs, and applies changes across files autonomously",
    reverse_engineered: true,
    smai_equivalent: "Code Architect agent exists but NO autonomous multi-file builder loop",
  },
  {
    layer: "Visual Editing",
    technologies: ["Click-to-modify UI", "Real-time visual edits", "No prompts needed"],
    capability: "Direct UI manipulation — select a component and adjust text, sizing, or styling",
    reverse_engineered: true,
    smai_equivalent: "Builder has preview canvas but NO click-to-modify visual editing",
  },
  {
    layer: "Deployment",
    technologies: ["Lovable Cloud", "One-click publish", "Custom domains"],
    capability: "Bundle hosting eliminates the biggest stopping point for builders",
    reverse_engineered: true,
    smai_equivalent: "Vercel/Railway manual setup — NO one-click deploy for generated apps",
  },
  {
    layer: "Templates",
    technologies: ["Production-ready templates", "Visual Edits customization", "Agent Mode extension"],
    capability: "Templates give a production-ready foundation users customize and extend",
    reverse_engineered: true,
    smai_equivalent: "TemplatePack entity + Visual Gallery exist but NO user-facing template marketplace",
  },
  {
    layer: "Billing",
    technologies: ["Credit-based pricing", "Daily + monthly credits", "Tiered plans"],
    capability: "Credit-based billing with free tier, pro, and business plans",
    reverse_engineered: true,
    smai_equivalent: "UsageBudgets page exists but NO live credit-based billing system",
  },
];

// ─── FORENSIC AUDIT — GAPS IN STRATEGIC MINDS AI vs BENCHMARK ────────────────
export const FORENSIC_AUDIT = [
  {
    id: "GAP-001",
    severity: "critical",
    category: "Payments",
    gap: "No live Stripe payment integration",
    benchmark_has: "Native Stripe — checkout flows, webhook handling, auto-generated database tables",
    smai_status: "MonetizationProfile entity defines pricing models but no live Stripe checkout or webhook handling exists",
    impact: "Generated apps cannot accept payments — the #1 revenue blocker",
    fill_technology: "Stripe Connect + Checkout + Webhook backend function",
    fill_status: "pending",
    autonomous: true,
  },
  {
    id: "GAP-002",
    severity: "critical",
    category: "Code Generation",
    gap: "No autonomous multi-file agent builder loop",
    benchmark_has: "Agent Mode — explores codebase, debugs proactively, applies changes across multiple files autonomously",
    smai_status: "Code Architect agent exists as a conversational template but has no autonomous build loop that writes, tests, and ships code",
    impact: "Every code task requires manual human execution — cannot scale",
    fill_technology: "Autonomous Coder Agent (tool-loop agent with file write/test/ship tools)",
    fill_status: "installing",
    autonomous: true,
  },
  {
    id: "GAP-003",
    severity: "critical",
    category: "Quality",
    gap: "No autonomous validation agent that gates releases",
    benchmark_has: "Independent validation — generated code is tested before deployment",
    smai_status: "RunValidation entity + 12-pass quality compiler exist but no autonomous agent that blocks bad code from shipping",
    impact: "No quality gate — broken code can ship to production",
    fill_technology: "Validation Agent (autonomous quality gate with mandatory pass/fail)",
    fill_status: "installing",
    autonomous: true,
  },
  {
    id: "GAP-004",
    severity: "high",
    category: "Code Ownership",
    gap: "No auto-sync of generated code to GitHub repos",
    benchmark_has: "Entire codebase syncs to GitHub — developers can take over at any point, no lock-in",
    smai_status: "GitHub connector is authorized (repo scope) but generated artifacts are not auto-pushed to repos",
    impact: "Generated code is trapped in the platform — no developer handoff path",
    fill_technology: "GitHub auto-sync backend function (push artifacts to connected repos)",
    fill_status: "pending",
    autonomous: true,
  },
  {
    id: "GAP-005",
    severity: "high",
    category: "Backend Provisioning",
    gap: "No auto-Supabase provisioning for generated apps",
    benchmark_has: "Generated apps auto-connect to Supabase — database, auth, storage ready instantly",
    smai_status: "Supabase connector is authorized but generated apps don't auto-provision a Supabase project",
    impact: "Generated apps have no backend — manual Supabase setup required",
    fill_technology: "Supabase auto-provision backend function (create project + schema + RLS)",
    fill_status: "pending",
    autonomous: true,
  },
  {
    id: "GAP-006",
    severity: "high",
    category: "Deployment",
    gap: "No one-click deploy for generated apps",
    benchmark_has: "Lovable Cloud — one-click publish with custom domains, hosting bundled",
    smai_status: "Vercel and Railway connectors exist but deploy is manual — no one-click publish from the builder",
    impact: "Users hit a wall between 'I'm done building' and 'it's live on the internet'",
    fill_technology: "One-click deploy backend function (Vercel project create + domain + publish)",
    fill_status: "pending",
    autonomous: true,
  },
  {
    id: "GAP-007",
    severity: "high",
    category: "Visual Editing",
    gap: "No click-to-modify visual editing in the builder",
    benchmark_has: "Visual Edits — select a component and adjust text, sizing, or styling directly without prompts",
    smai_status: "Builder has a preview canvas and inspector but no direct click-to-modify on rendered elements",
    impact: "Non-technical users cannot fine-tune UI without writing prompts",
    fill_technology: "Visual edit overlay (click-to-select + inline edit panel on preview canvas)",
    fill_status: "pending",
    autonomous: false,
  },
  {
    id: "GAP-008",
    severity: "medium",
    category: "Templates",
    gap: "No user-facing template marketplace",
    benchmark_has: "Production-ready templates users browse, customize with Visual Edits, and extend with Agent Mode",
    smai_status: "TemplatePack entity + Visual Gallery exist but no public marketplace where users browse and one-click-start from templates",
    impact: "Users start from scratch instead of a production-ready foundation",
    fill_technology: "Template marketplace page (browse + one-click fork into a new project)",
    fill_status: "pending",
    autonomous: false,
  },
  {
    id: "GAP-009",
    severity: "medium",
    category: "Billing",
    gap: "No live credit-based billing system",
    benchmark_has: "Credit-based pricing — free tier, pro, business plans with daily + monthly credits",
    smai_status: "UsageBudgets page tracks usage but no live credit metering or paywall",
    impact: "No monetization path for the platform itself",
    fill_technology: "Credit metering + Stripe subscription billing for the platform",
    fill_status: "pending",
    autonomous: false,
  },
  {
    id: "GAP-010",
    severity: "medium",
    category: "Real-time",
    gap: "No real-time collaborative editing",
    benchmark_has: "Chat + Visual Edits enable collaborative iteration",
    smai_status: "Single-user builder — no multi-user real-time collaboration",
    impact: "Teams cannot co-build in real time",
    fill_technology: "Actors (realtime rooms) for collaborative builder sessions",
    fill_status: "pending",
    autonomous: false,
  },
];

// ─── AUTONOMOUS AGENTS TO INSTALL ───────────────────────────────────────────
export const AUTONOMOUS_AGENTS = [
  {
    key: "autonomous_coder",
    name: "Autonomous Coder",
    icon: "⚙️",
    description: "Autonomous coding agent that writes, tests, and ships production code across the full stack. Takes ownership of a gap, explores the codebase, writes the code, runs validation, and ships — all autonomously.",
    source: "Code Architect super agent (enhanced with autonomous tool-loop)",
    config_file: "base44/agents/autonomous_coder.jsonc",
    install_status: "installing",
    tools: ["writeFile", "readFile", "runTests", "executeGenerator", "logFactoryEvent"],
    target_gaps: ["GAP-002", "GAP-004", "GAP-005", "GAP-006"],
    mandate: "100% code mandatory — every function, button, and flow must actually work. No stubs. No placeholders. No partial implementations.",
    speed: "fast",
  },
  {
    key: "validation_agent",
    name: "Validation Agent",
    icon: "🛡️",
    description: "Autonomous validation agent that gates every release. Runs the 12-pass quality compiler, independent schema/lint/typecheck/compile/unit/integration/e2e/visual/a11y/security/dependency/secret checks, and blocks any code that fails mandatory layers from shipping.",
    source: "RunValidation entity + 12-pass quality compiler (enhanced with autonomous agent)",
    config_file: "base44/agents/validation_agent.jsonc",
    install_status: "installing",
    tools: ["readFile", "runValidation", "logFactoryEvent", "createRepairTask"],
    target_gaps: ["GAP-003"],
    mandate: "100% code mandatory — fail-closed. No code ships until all mandatory validation layers PASS.",
    speed: "fast",
  },
];

// ─── GAP-FILL INSTALLATION PLAN ─────────────────────────────────────────────
export const GAP_FILL_PLAN = FORENSIC_AUDIT.map((gap) => ({
  gap_id: gap.id,
  severity: gap.severity,
  technology: gap.fill_technology,
  status: gap.fill_status,
  autonomous: gap.autonomous,
  assigned_agent: gap.autonomous ? "autonomous_coder" : "manual",
}));

// ─── BENCHMARK SCORECARD ────────────────────────────────────────────────────
export const SCORECARD = {
  benchmark: BENCHMARK.name,
  total_gaps: FORENSIC_AUDIT.length,
  critical: FORENSIC_AUDIT.filter((g) => g.severity === "critical").length,
  high: FORENSIC_AUDIT.filter((g) => g.severity === "high").length,
  medium: FORENSIC_AUDIT.filter((g) => g.severity === "medium").length,
  agents_installing: AUTONOMOUS_AGENTS.filter((a) => a.install_status === "installing").length,
  autonomous_gaps: FORENSIC_AUDIT.filter((g) => g.autonomous).length,
  manual_gaps: FORENSIC_AUDIT.filter((g) => !g.autonomous).length,
  mandate: "100% code mandatory — every gap filled with working, tested, production code. No stubs. No placeholders. Running fast as possible.",
};

export function getGapById(id) {
  return FORENSIC_AUDIT.find((g) => g.id === id);
}

export function getAgentByKey(key) {
  return AUTONOMOUS_AGENTS.find((a) => a.key === key);
}