// Provisioning Template Registry — describes what must exist AND how it is provisioned.
// All operations are dry-run by default. No paid/production/secret/DNS/permission
// action executes without operator approval.

export const PROVISIONING_TEMPLATES = {
  business: [
    { id: "biz-new-company", name: "New Company", steps: ["Register legal entity", "Set up accounting", "Create org chart"], rollback: ["Dissolve entity", "Archive records"] },
    { id: "biz-new-client", name: "New Client", steps: ["Create client record", "Assign account manager", "Provision workspace"], rollback: ["Archive client", "Revoke access"] },
    { id: "biz-new-brand", name: "New Brand", steps: ["Define brand spec", "Generate token set", "Lock visual identity"], rollback: ["Revert to previous brand"] },
    { id: "biz-new-division", name: "New Division", steps: ["Define division", "Assign leads", "Provision sub-workspaces"], rollback: ["Merge back"] },
    { id: "biz-new-location", name: "New Location", steps: ["Add location record", "Configure local settings", "Assign staff"], rollback: ["Archive location"] },
    { id: "biz-new-franchise", name: "New Franchise", steps: ["Franchise agreement", "Provision tenant", "Brand localization"], rollback: ["Terminate franchise"] },
    { id: "biz-new-product", name: "New Product", steps: ["Define product spec", "Create catalog entry", "Set pricing"], rollback: ["Discontinue product"] },
    { id: "biz-new-saas-tenant", name: "New SaaS Tenant", steps: ["Create tenant", "Assign plan", "Provision data isolation"], rollback: ["Purge tenant data"] },
  ],
  user: [
    { id: "user-owner", name: "Owner", roles: ["owner"], permissions: ["*"], rollback: ["Transfer ownership"] },
    { id: "user-admin", name: "Administrator", roles: ["admin"], permissions: ["manage_users", "manage_billing", "manage_config"], rollback: ["Demote to user"] },
    { id: "user-manager", name: "Manager", roles: ["manager"], permissions: ["manage_team", "view_reports"], rollback: ["Remove manager role"] },
    { id: "user-employee", name: "Employee", roles: ["employee"], permissions: ["use_apps", "edit_own"], rollback: ["Deactivate"] },
    { id: "user-contractor", name: "Contractor", roles: ["contractor"], permissions: ["limited_access"], rollback: ["Revoke access"] },
    { id: "user-client", name: "Client", roles: ["client"], permissions: ["portal_access"], rollback: ["Close portal"] },
    { id: "user-vendor", name: "Vendor", roles: ["vendor"], permissions: ["supply_portal"], rollback: ["Terminate vendor"] },
    { id: "user-customer", name: "Customer", roles: ["customer"], permissions: ["purchase", "self_service"], rollback: ["Anonymize account"] },
    { id: "user-auditor", name: "Read-only Auditor", roles: ["auditor"], permissions: ["read_all", "export_audit"], rollback: ["Revoke audit access"] },
  ],
  application: [
    { id: "app-web", name: "Web Application", steps: ["Create Base44 app", "Configure routes", "Set auth"], rollback: ["Archive app"] },
    { id: "app-pwa", name: "PWA", steps: ["Create app", "Add manifest", "Service worker", "Install prompt"], rollback: ["Remove PWA config"] },
    { id: "app-mobile-first", name: "Mobile-first Web App", steps: ["Create app", "Mobile patterns", "Responsive transforms"], rollback: ["Revert layout"] },
    { id: "app-saas", name: "SaaS Application", steps: ["Multi-tenant setup", "Billing", "RBAC", "Onboarding"], rollback: ["Downgrade to single-tenant"] },
    { id: "app-client-portal", name: "Client Portal", steps: ["Portal pages", "Auth", "RLS per client"], rollback: ["Close portal"] },
    { id: "app-admin-portal", name: "Admin Portal", steps: ["Admin routes", "RBAC admin", "Audit log"], rollback: ["Restrict access"] },
    { id: "app-marketplace", name: "Marketplace", steps: ["Listings", "Search", "Transactions", "Reviews"], rollback: ["Disable marketplace"] },
    { id: "app-ecommerce", name: "Ecommerce", steps: ["Catalog", "Cart", "Checkout", "Payments"], rollback: ["Disable store"] },
    { id: "app-dashboard", name: "Dashboard", steps: ["Data sources", "Widgets", "Filters", "Export"], rollback: ["Reset dashboard"] },
    { id: "app-internal", name: "Internal System", steps: ["Workflows", "Approvals", "Reporting"], rollback: ["Decommission"] },
  ],
  infrastructure: [
    { id: "infra-github-repo", name: "GitHub Repository", steps: ["Create repo", "Branch structure", "PR template"], rollback: ["Archive repo"] },
    { id: "infra-vercel-project", name: "Vercel Project", steps: ["Link repo", "Build config", "Env vars (dry-run)"], rollback: ["Delete project"] },
    { id: "infra-preview-env", name: "Preview Environment", steps: ["Create preview", "Seed data", "Share link"], rollback: ["Tear down preview"] },
    { id: "infra-prod-env", name: "Production Environment", steps: ["Approval gate", "Deploy", "Smoke test"], rollback: ["Rollback deploy"] },
    { id: "infra-supabase", name: "Supabase Project", steps: ["Create project", "Database", "Storage", "Auth"], rollback: ["Pause project"] },
    { id: "infra-database", name: "Database", steps: ["Define schema", "Migrations", "RLS policies"], rollback: ["Revert migration"] },
    { id: "infra-storage", name: "Storage", steps: ["Create buckets", "Set policies", "CDN"], rollback: ["Empty bucket"] },
    { id: "infra-auth", name: "Authentication", steps: ["Configure providers", "RBAC", "Session policy"], rollback: ["Reset auth config"] },
    { id: "infra-railway-worker", name: "Railway Worker/Service", steps: ["Create service", "Deploy worker", "Set secrets (dry-run)"], rollback: ["Stop service"] },
    { id: "infra-ai-gateway", name: "AI Gateway", steps: ["Configure models", "Rate limits", "Budget caps"], rollback: ["Disable gateway"] },
    { id: "infra-workflow", name: "Scheduled Workflow", steps: ["Define trigger", "Steps", "Deploy"], rollback: ["Pause workflow"] },
    { id: "infra-queue", name: "Queue", steps: ["Create queue", "Consumers", "DLQ"], rollback: ["Drain queue"] },
    { id: "infra-webhook", name: "Webhook Infrastructure", steps: ["Endpoint", "Signing", "Retry policy"], rollback: ["Disable webhooks"] },
    { id: "infra-logging", name: "Logging", steps: ["Log streams", "Retention", "Alerts"], rollback: ["Reset logging"] },
    { id: "infra-monitoring", name: "Monitoring", steps: ["Uptime checks", "Metrics", "Dashboards"], rollback: ["Remove monitors"] },
    { id: "infra-analytics", name: "Analytics", steps: ["Events", "Funnels", "Reports"], rollback: ["Disable tracking"] },
  ],
  google_workspace: [
    { id: "gw-drive-hierarchy", name: "Drive Folder Hierarchy", steps: ["Top-level folders", "Sharing rules"], rollback: ["Remove folders"] },
    { id: "gw-project-folder", name: "Project Folder", steps: ["Create folder", "Templates", "Permissions"], rollback: ["Archive folder"] },
    { id: "gw-client-folder", name: "Client Folder", steps: ["Create folder", "Share with client"], rollback: ["Revoke share"] },
    { id: "gw-shared-docs", name: "Shared Documents", steps: ["Create docs", "Share link"], rollback: ["Unshare"] },
    { id: "gw-sheet", name: "Google Sheet", steps: ["Create sheet", "Structure", "Permissions"], rollback: ["Delete sheet"] },
    { id: "gw-doc", name: "Google Doc", steps: ["Create doc", "Template", "Share"], rollback: ["Delete doc"] },
    { id: "gw-calendar", name: "Google Calendar", steps: ["Create calendar", "Events", "Reminders"], rollback: ["Delete calendar"] },
    { id: "gw-gmail-workflows", name: "Gmail Workflows", steps: ["Labels", "Filters", "Templates"], rollback: ["Reset labels"] },
    { id: "gw-chat-room", name: "Google Chat Room", steps: ["Create space", "Add members", "Webhooks"], rollback: ["Archive space"] },
    { id: "gw-contacts", name: "Contact Structure", steps: ["Groups", "Import", "Tags"], rollback: ["Clear groups"] },
  ],
  domain: [
    { id: "dom-assignment", name: "Domain Assignment", steps: ["Assign domain", "Verify ownership"], rollback: ["Release domain"], approvalRequired: true },
    { id: "dom-dns", name: "DNS Requirements", steps: ["A records", "CNAME", "MX"], rollback: ["Revert DNS"], approvalRequired: true },
    { id: "dom-ssl", name: "SSL", steps: ["Provision cert", "Auto-renew"], rollback: ["Remove cert"] },
    { id: "dom-redirects", name: "Redirect Strategy", steps: ["301 rules", "Legacy paths"], rollback: ["Remove redirects"] },
    { id: "dom-subdomains", name: "Subdomains", steps: ["Define subdomains", "DNS"], rollback: ["Remove subdomains"], approvalRequired: true },
    { id: "dom-staging", name: "Staging Domain", steps: ["Assign staging", "SSL"], rollback: ["Release staging"] },
    { id: "dom-production", name: "Production Domain", steps: ["Approval gate", "Point DNS", "SSL"], rollback: ["Revert DNS"], approvalRequired: true },
    { id: "dom-search-console", name: "Google Search Console", steps: ["Verify", "Sitemap", "Monitor"], rollback: ["Remove property"] },
    { id: "dom-analytics", name: "Google Analytics", steps: ["Create property", "Events", "Goals"], rollback: ["Remove property"] },
    { id: "dom-sitemap", name: "Sitemap", steps: ["Generate", "Submit"], rollback: ["Remove sitemap"] },
    { id: "dom-robots", name: "robots.txt", steps: ["Write rules", "Deploy"], rollback: ["Revert"] },
  ],
  connector: [
    { id: "conn-google", name: "Google", steps: ["OAuth", "Scopes", "Test"], rollback: ["Revoke token"] },
    { id: "conn-github", name: "GitHub", steps: ["OAuth", "Repo access"], rollback: ["Revoke"] },
    { id: "conn-vercel", name: "Vercel", steps: ["OAuth", "Team access"], rollback: ["Revoke"] },
    { id: "conn-supabase", name: "Supabase", steps: ["OAuth", "Project access"], rollback: ["Revoke"] },
    { id: "conn-railway", name: "Railway", steps: ["OAuth", "Service access"], rollback: ["Revoke"] },
    { id: "conn-shopify", name: "Shopify", steps: ["App install", "Scopes"], rollback: ["Uninstall"] },
    { id: "conn-stripe", name: "Stripe", steps: ["API keys (dry-run)", "Webhooks"], rollback: ["Remove keys"] },
    { id: "conn-hubspot", name: "HubSpot", steps: ["OAuth", "Scopes"], rollback: ["Revoke"] },
    { id: "conn-slack", name: "Slack", steps: ["OAuth", "Channels"], rollback: ["Revoke"] },
    { id: "conn-gw", name: "Google Workspace", steps: ["Admin OAuth", "Domain-wide delegation"], rollback: ["Revoke"] },
  ],
  ai_agent: [
    { id: "agent-assistant", name: "AI Assistant", role: "assistant", objective: "General help", tools: [], permissions: ["read"], rollback: ["Disable agent"] },
    { id: "agent-supervisor", name: "Supervisor Agent", role: "supervisor", objective: "Orchestrate specialists", tools: ["delegate"], permissions: ["read", "delegate"], rollback: ["Disable supervisor"] },
    { id: "agent-specialist", name: "Specialist Agent", role: "specialist", objective: "Domain task", tools: ["entity_crud"], permissions: ["read", "write"], rollback: ["Disable agent"] },
    { id: "agent-research", name: "Research Agent", role: "research", objective: "Gather information", tools: ["web_search"], permissions: ["read"], rollback: ["Disable agent"] },
    { id: "agent-coding", name: "Coding Agent", role: "coding", objective: "Implement features", tools: ["code_edit"], permissions: ["read", "write"], rollback: ["Disable agent"] },
    { id: "agent-validator", name: "Validator Agent", role: "validator", objective: "Verify outputs", tools: ["lint", "test"], permissions: ["read"], rollback: ["Disable agent"] },
    { id: "agent-sales", name: "Sales Agent", role: "sales", objective: "Qualify + nurture leads", tools: ["crm"], permissions: ["read", "write"], rollback: ["Disable agent"] },
    { id: "agent-marketing", name: "Marketing Agent", role: "marketing", objective: "Content + campaigns", tools: ["content_gen"], permissions: ["read", "write"], rollback: ["Disable agent"] },
    { id: "agent-support", name: "Customer-service Agent", role: "support", objective: "Resolve tickets", tools: ["kb", "ticketing"], permissions: ["read", "write"], rollback: ["Disable agent"] },
    { id: "agent-analyst", name: "Data Analyst Agent", role: "analyst", objective: "Insights + reports", tools: ["query", "chart"], permissions: ["read"], rollback: ["Disable agent"] },
    { id: "agent-rag", name: "Knowledge/RAG Agent", role: "rag", objective: "Answer from knowledge", tools: ["retriever"], permissions: ["read"], rollback: ["Disable agent"] },
    { id: "agent-swarm", name: "AI Swarm", role: "swarm", objective: "Multi-agent coordination", tools: ["message_bus"], permissions: ["read", "delegate"], rollback: ["Disable swarm"] },
  ],
};

export function buildDryRunManifest(templateType, templateId, projectId) {
  const group = PROVISIONING_TEMPLATES[templateType];
  if (!group) return null;
  const tmpl = group.find((t) => t.id === templateId);
  if (!tmpl) return null;
  return {
    project_id: projectId,
    template_id: templateId,
    template_type: templateType,
    dry_run: true,
    name: tmpl.name,
    items: (tmpl.steps || []).map((s, i) => ({ step: i + 1, action: s, status: "dry_run", approval_required: !!tmpl.approvalRequired })),
    rollback_plan: tmpl.rollback || [],
    status: "dry_run",
  };
}