// Super Agent Registry — the universal source of truth.
// Each super agent is BOTH an operator (system prompt + tools) AND a versioned template
// (variables_schema + file_tree). Bootstrap a ready-to-go packet by answering the
// questionnaire (logo, accent color, content, images, variables) — deterministic
// substitution runs today; AI enrichment steps are gated NOT_CONFIGURED until credits reset.

export const REGISTRY_VERSION = "1.0.0";

const COMMON_VARIABLES = [
  { key: "business_name", label: "Business Name", type: "text", required: true, help: "The brand / company name." },
  { key: "tagline", label: "Tagline", type: "text", required: false, help: "One-line value proposition." },
  { key: "logo_url", label: "Logo URL", type: "image", required: true, help: "Public URL to the logo image." },
  { key: "accent_color", label: "Accent Color", type: "color", required: true, default: "#FFEA00", help: "Primary brand accent (hex)." },
  { key: "industry", label: "Industry", type: "text", required: true, help: "e.g. HVAC, dental, SaaS, legal." },
  { key: "primary_goal", label: "Primary Goal", type: "select", required: true, default: "lead_generation",
    options: ["lead_generation", "ecommerce_sales", "bookings", "content_subscribers", "brand_awareness"], help: "What the built system must drive." },
  { key: "contact_email", label: "Contact Email", type: "text", required: true, help: "Public contact address." },
  { key: "phone", label: "Phone", type: "text", required: false, help: "Public phone number." },
  { key: "hero_image", label: "Hero Image URL", type: "image", required: false, help: "Public URL to the hero/cover image." },
  { key: "about_text", label: "About Text", type: "textarea", required: false, help: "Short about paragraph." },
];

export const SUPER_AGENTS = [
  {
    key: "orchestrator", name: "The Orchestrator", icon: "🧠", category: "Apex", apex: true, version: "1.0.0",
    description: "The apex master agent. Give it any business goal — it decomposes the work across stages, dispatches the specialist agents, sequences the critical path, and reports a unified mission brief.",
    skills: ["Decompose", "Dispatch", "Sequence", "Track", "Escalate", "Mission Control"],
    tools: ["dispatchAgent", "readRegistry", "createRunPlan", "trackMission", "escalate"],
    system_prompt: "You are The Orchestrator, the apex master agent of the Xtreme AI Business Factory. Given any business goal, decompose it into staged work, dispatch the right specialist super-agents, sequence the critical path, track progress, escalate blockers, and report a unified mission brief. You operate over a universal, versioned source of truth: the factory registry. Never fake success — if a specialist or integration is not configured, say so explicitly.",
    template: {
      mode: "file_tree",
      label: "Mission Plan Template",
      variables_schema: [
        ...COMMON_VARIABLES,
        { key: "mission_goal", label: "Mission Goal", type: "textarea", required: true, help: "The single business goal this mission pursues." },
        { key: "stages", label: "Stages (comma separated)", type: "text", required: false, default: "Discover, Build, Grow, Operate", help: "Pipeline stages to sequence." },
      ],
      files: [
        { path: "mission/MISSION.md", content: `# Mission: {{business_name}}\n\n**Goal:** {{mission_goal}}\n**Industry:** {{industry}}\n**Primary goal:** {{primary_goal}}\n**Stages:** {{stages}}\n\n## Critical Path\n1. Discover — Brand Guardian audits positioning for {{business_name}}.\n2. Build — Code Architect scaffolds the {{industry}} system.\n3. Grow — Sales Engine + Social Strategist run outbound + content.\n4. Operate — Growth Operator monitors analytics for {{contact_email}}.\n\n## Brand Snapshot\n- Logo: {{logo_url}}\n- Accent: {{accent_color}}\n- Tagline: {{tagline}}\n- Hero: {{hero_image}}\n\n> Generated by The Orchestrator template v1.0.0. Swap variables and re-render.` },
        { path: "mission/brand.config.json", content: `{ "business_name": "{{business_name}}", "accent_color": "{{accent_color}}", "logo_url": "{{logo_url}}", "industry": "{{industry}}", "primary_goal": "{{primary_goal}}" }` },
      ],
    },
  },
  {
    key: "growth_operator", name: "Growth Operator", icon: "🛡️", category: "Operate", flagship: true, version: "1.0.0",
    description: "Autonomous Google growth engine — takes any URL end-to-end through Search Console, GA4, GTM, sitemaps, index coverage, competitor intelligence and continuous monitoring.",
    skills: ["Search Console", "GA4", "GTM", "Sitemaps", "Indexing", "Competitors", "Analytics"],
    tools: ["readSearchConsole", "readGA4", "manageGTM", "submitSitemap", "auditIndex", "analyzeCompetitors"],
    system_prompt: "You are the Growth Operator. Take any URL end-to-end through Search Console, GA4, GTM, sitemaps, index coverage, competitor intelligence and continuous monitoring. Report evidence-based findings; never claim a metric you did not measure.",
    template: {
      mode: "file_tree",
      label: "Growth Audit Template",
      variables_schema: [
        ...COMMON_VARIABLES,
        { key: "target_url", label: "Target URL", type: "text", required: true, help: "The site to grow." },
        { key: "competitors", label: "Competitors (comma separated)", type: "text", required: false, help: "Domains to benchmark." },
      ],
      files: [
        { path: "growth/AUDIT.md", content: `# Growth Audit — {{target_url}}\n\nOwner: {{business_name}} ({{contact_email}})\nIndustry: {{industry}}\nAccent: {{accent_color}}\n\n## Checklist\n- [ ] Search Console verified\n- [ ] GA4 connected\n- [ ] GTM container published\n- [ ] Sitemap submitted\n- [ ] Index coverage reported\n- [ ] Competitors: {{competitors}}\n\n> Deterministic template. AI enrichment (live Search Console/GA4 reads) runs when the AI Gateway is configured.` },
        { path: "growth/gtm.config.json", content: `{ "site": "{{target_url}}", "container_name": "{{business_name}}", "accent": "{{accent_color}}" }` },
      ],
    },
  },
  {
    key: "code_architect", name: "Code Architect", icon: "⚙️", category: "Build", version: "1.0.0",
    description: "Elite staff-engineer pair. Writes, reviews, refactors, debugs and ships production code across the full stack. Creates SystemBuild records and dispatches build tasks.",
    skills: ["React", "TypeScript", "Python", "Refactor", "Debug", "SystemBuild", "Tests"],
    tools: ["writeFile", "readFile", "runTests", "createSystemBuild", "dispatchBuildTask"],
    system_prompt: "You are the Code Architect, an elite staff-engineer pair. Write, review, refactor, debug and ship production code across the full stack. Create SystemBuild records and dispatch build tasks. Never ship a stub — if a component is not implemented, return NOT_CONFIGURED.",
    template: {
      mode: "file_tree",
      label: "System Scaffold Template",
      variables_schema: [
        ...COMMON_VARIABLES,
        { key: "platforms", label: "Platforms (comma separated)", type: "text", required: false, default: "mobile-web, desktop-web", help: "Target platforms." },
        { key: "stack", label: "Stack", type: "select", required: true, default: "react-tailwind",
          options: ["react-tailwind", "next-supabase", "react-native", "python-fastapi"], help: "Primary technology stack." },
      ],
      files: [
        { path: "system/README.md", content: `# {{business_name}} System\n\nStack: {{stack}}\nPlatforms: {{platforms}}\nGoal: {{primary_goal}}\n\n## Scaffold\n- Brand: {{logo_url}} / accent {{accent_color}}\n- Contact: {{contact_email}} / {{phone}}\n- About: {{about_text}}\n\n> Swap variables and re-render. AI code generation runs when the AI Gateway is configured.` },
        { path: "system/brand.tokens.json", content: `{ "brand": "{{business_name}}", "accent": "{{accent_color}}", "logo": "{{logo_url}}", "hero": "{{hero_image}}", "stack": "{{stack}}", "platforms": [{{platforms}}] }` },
      ],
    },
  },
  {
    key: "social_strategist", name: "Social Strategist", icon: "📣", category: "Grow", version: "1.0.0",
    description: "Owns the full social lifecycle — strategy, platform-native content, calendars, engagement playbooks and performance analysis. Dispatches social automation tasks.",
    skills: ["Instagram", "TikTok", "LinkedIn", "Content", "Calendar", "Engagement", "Automation"],
    tools: ["planCalendar", "draftContent", "schedulePost", "analyzeEngagement"],
    system_prompt: "You are the Social Strategist. Own the full social lifecycle — strategy, platform-native content, calendars, engagement playbooks and performance analysis. Dispatch social automation tasks. Platform-native only; never post without a calendar entry.",
    template: {
      mode: "file_tree",
      label: "Social Calendar Template",
      variables_schema: [
        ...COMMON_VARIABLES,
        { key: "platforms", label: "Platforms (comma separated)", type: "text", required: false, default: "Instagram, TikTok, LinkedIn", help: "Active social platforms." },
        { key: "post_frequency", label: "Post Frequency", type: "select", required: true, default: "3x_week",
          options: ["daily", "3x_week", "weekly", "biweekly"], help: "How often to publish." },
      ],
      files: [
        { path: "social/CALENDAR.md", content: `# Social Calendar — {{business_name}}\n\nPlatforms: {{platforms}}\nFrequency: {{post_frequency}}\nAccent: {{accent_color}}\n\n## Pillars\n1. Educate ({{industry}} tips)\n2. Showcase ({{tagline}})\n3. Convert (CTA → {{primary_goal}})\n\n> AI content drafts run when the AI Gateway is configured.` },
        { path: "social/voice.json", content: `{ "brand": "{{business_name}}", "accent": "{{accent_color}}", "platforms": [{{platforms}}], "frequency": "{{post_frequency}}" }` },
      ],
    },
  },
  {
    key: "sales_engine", name: "Sales Engine", icon: "🚀", category: "Grow", version: "1.0.0",
    description: "Revenue super-agent from prospect to closed deal — ICPs, outreach sequences, qualification, pipeline, follow-up and closing playbooks. Dispatches outreach automation tasks.",
    skills: ["Outbound", "Sequences", "MEDDIC", "Pipeline", "Forecasting", "Closing", "Automation"],
    tools: ["buildICP", "writeSequence", "qualifyLead", "updatePipeline", "scheduleFollowUp"],
    system_prompt: "You are the Sales Engine. Move prospects from first touch to closed deal — ICPs, outreach sequences, qualification, pipeline, follow-up and closing playbooks. Dispatch outreach automation tasks. Never fabricate a reply or a meeting.",
    template: {
      mode: "file_tree",
      label: "Sales Playbook Template",
      variables_schema: [
        ...COMMON_VARIABLES,
        { key: "icp", label: "Ideal Customer Profile", type: "textarea", required: true, help: "Who you sell to." },
        { key: "offer", label: "Core Offer", type: "text", required: true, help: "The primary product/service offer." },
      ],
      files: [
        { path: "sales/PLAYBOOK.md", content: `# Sales Playbook — {{business_name}}\n\nICP: {{icp}}\nOffer: {{offer}}\nGoal: {{primary_goal}}\nContact: {{contact_email}} / {{phone}}\n\n## Sequence\n1. Touch 1 — Educate on {{industry}}\n2. Touch 2 — Share {{tagline}}\n3. Touch 3 — CTA: {{offer}}\n\n> AI outreach drafts run when the AI Gateway is configured.` },
        { path: "sales/pipeline.json", content: `{ "brand": "{{business_name}}", "icp": "{{icp}}", "offer": "{{offer}}", "accent": "{{accent_color}}" }` },
      ],
    },
  },
  {
    key: "brand_guardian", name: "Brand Guardian", icon: "✦", category: "Discover", version: "1.0.0",
    description: "Protects and amplifies the brand — voice, messaging, content strategy, copywriting and creative direction across every touchpoint. Dispatches content production tasks.",
    skills: ["Voice", "Copy", "Content", "Positioning", "Style Guide", "Audit"],
    tools: ["auditVoice", "writeCopy", "buildStyleGuide", "planContent"],
    system_prompt: "You are the Brand Guardian. Protect and amplify the brand — voice, messaging, content strategy, copywriting and creative direction across every touchpoint. Dispatch content production tasks. Keep voice consistent with the brand snapshot.",
    template: {
      mode: "file_tree",
      label: "Brand Book Template",
      variables_schema: [
        ...COMMON_VARIABLES,
        { key: "voice", label: "Brand Voice", type: "select", required: true, default: "confident",
          options: ["confident", "friendly", "authoritative", "playful", "luxury"], help: "Tone of voice." },
        { key: "audience", label: "Target Audience", type: "text", required: true, help: "Who the brand speaks to." },
      ],
      files: [
        { path: "brand/BRAND_BOOK.md", content: `# Brand Book — {{business_name}}\n\nTagline: {{tagline}}\nVoice: {{voice}}\nAudience: {{audience}}\nAccent: {{accent_color}}\nLogo: {{logo_url}}\nHero: {{hero_image}}\nAbout: {{about_text}}\n\n## Voice Rules\n- Lead with the benefit to {{audience}}.\n- Never contradict the {{voice}} tone.\n- Accent {{accent_color}} only for primary CTAs.\n\n> AI copywriting runs when the AI Gateway is configured.` },
        { path: "brand/tokens.json", content: `{ "brand": "{{business_name}}", "accent": "{{accent_color}}", "logo": "{{logo_url}}", "voice": "{{voice}}", "audience": "{{audience}}" }` },
      ],
    },
  },
  {
    key: "replicator", name: "The Replicator", icon: "🧬", category: "Apex", version: "1.0.0",
    description: "Fleet cloning super-agent. Clones and deploys the entire Xtreme AI agent architecture to new domains, systems, and Base44 apps — at any scale. Provisions SystemBuilds, launches BatchOperations, and dispatches replication tasks.",
    skills: ["Clone", "Provision", "Batch Deploy", "Blueprint", "Scale", "Replicate"],
    tools: ["cloneBlueprint", "provisionApp", "launchBatch", "dispatchReplication"],
    system_prompt: "You are The Replicator. Clone and deploy the Xtreme AI agent architecture to new domains, systems, and Base44 apps at any scale. Provision SystemBuilds, launch BatchOperations, and dispatch replication tasks. Never claim a clone succeeded without a provisioned target.",
    template: {
      mode: "file_tree",
      label: "Replication Blueprint Template",
      variables_schema: [
        ...COMMON_VARIABLES,
        { key: "target_count", label: "Number of Clones", type: "number", required: true, default: 1, help: "How many instances to provision." },
        { key: "deploy_targets", label: "Deploy Targets (comma separated)", type: "text", required: false, default: "github", help: "Where clones ship." },
      ],
      files: [
        { path: "replicate/BLUEPRINT.md", content: `# Replication Blueprint — {{business_name}}\n\nClones: {{target_count}}\nTargets: {{deploy_targets}}\nIndustry: {{industry}}\nAccent: {{accent_color}}\n\n## Steps\n1. Clone agent architecture\n2. Provision {{target_count}} app(s)\n3. Apply brand ({{logo_url}}, {{accent_color}})\n4. Batch deploy to {{deploy_targets}}\n\n> Provisioning runs when adapters are configured.` },
        { path: "replicate/fleet.json", content: `{ "brand": "{{business_name}}", "count": {{target_count}}, "targets": [{{deploy_targets}}], "accent": "{{accent_color}}" }` },
      ],
    },
  },
  {
    key: "swarm", name: "The Swarm", icon: "🐝", category: "Apex", version: "1.0.0",
    description: "Parallel coordination super-agent. Takes a single goal, splits it into independent subtasks, dispatches them across the specialist fleet simultaneously, aggregates results, and reports a unified output. Maximum throughput.",
    skills: ["Parallel", "Decompose", "Dispatch All", "Aggregate", "Throughput", "Scale"],
    tools: ["splitGoal", "dispatchAll", "aggregateResults", "reportUnified"],
    system_prompt: "You are The Swarm. Take a single goal, split it into independent subtasks, dispatch them across the specialist fleet simultaneously, aggregate results, and report a unified output. Maximize throughput. Report partial failures honestly.",
    template: {
      mode: "file_tree",
      label: "Swarm Plan Template",
      variables_schema: [
        ...COMMON_VARIABLES,
        { key: "mission_goal", label: "Single Goal", type: "textarea", required: true, help: "The goal to parallelize." },
        { key: "subtask_count", label: "Subtask Count", type: "number", required: true, default: 4, help: "How many parallel subtasks." },
      ],
      files: [
        { path: "swarm/PLAN.md", content: `# Swarm Plan — {{business_name}}\n\nGoal: {{mission_goal}}\nSubtasks: {{subtask_count}}\nIndustry: {{industry}}\n\n## Dispatch\n- Split goal into {{subtask_count}} independent subtasks\n- Dispatch all specialists in parallel\n- Aggregate results → unified brief for {{contact_email}}\n\n> Parallel dispatch runs when the agent runtime is configured.` },
        { path: "swarm/config.json", content: `{ "brand": "{{business_name}}", "goal": "{{mission_goal}}", "subtasks": {{subtask_count}}, "accent": "{{accent_color}}" }` },
      ],
    },
  },
];

export const AGENT_CATEGORIES = ["All", "Apex", "Discover", "Build", "Grow", "Operate"];

export function getAgent(key) {
  return SUPER_AGENTS.find((a) => a.key === key);
}

// Deterministic variable substitution: replaces {{var}} with answers, leaves unknowns visible.
export function renderTemplate(content, answers) {
  return content.replace(/\{\{(\w+)\}\}/g, (m, k) => {
    const v = answers[k];
    if (v === undefined || v === null || v === "") return `{{${k}:UNSET}}`;
    return String(v);
  });
}

// Validate answers against a variables_schema; returns {missing, errors}.
export function validateAnswers(schema, answers) {
  const missing = [];
  const errors = [];
  for (const v of schema) {
    const val = answers[v.key];
    if (v.required && (val === undefined || val === null || val === "")) {
      missing.push(v.key);
    }
    if (v.type === "color" && val && !/^#[0-9a-fA-F]{3,8}$/.test(val)) {
      errors.push(`${v.key} must be a hex color`);
    }
    if (v.type === "number" && val !== "" && val !== undefined && isNaN(Number(val))) {
      errors.push(`${v.key} must be a number`);
    }
  }
  return { missing, errors };
}

// Deterministic bootstrap: render the agent's template files with answers.
// Returns a ready-to-go packet. AI enrichment is NOT_CONFIGURED (honest).
export async function bootstrapAgent(agentKey, answers) {
  const agent = getAgent(agentKey);
  if (!agent) throw new Error(`Unknown agent: ${agentKey}`);
  const schema = agent.template.variables_schema;
  const { missing, errors } = validateAnswers(schema, answers);
  const files = agent.template.files.map((f) => ({
    path: f.path,
    content: renderTemplate(f.content, answers),
  }));
  // SHA-256 per file via Web Crypto (deterministic integrity).
  const hashed = await Promise.all(files.map(async (f) => {
    const buf = new TextEncoder().encode(f.content);
    const digest = await crypto.subtle.digest("SHA-256", buf);
    const sha256 = Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
    return { ...f, sha256 };
  }));
  return {
    agent_key: agent.key,
    agent_name: agent.name,
    template_label: agent.template.label,
    template_version: agent.version,
    registry_version: REGISTRY_VERSION,
    generated_at: new Date().toISOString(),
    variables: answers,
    validation: { missing_required: missing, errors, ready: missing.length === 0 && errors.length === 0 },
    files: hashed,
    ai_enrichment: { status: "NOT_CONFIGURED", reason: "AI Gateway credits exhausted until 2026-10-12. Deterministic template rendered; AI steps (copywriting, code gen, outreach) re-enable when credits reset." },
  };
}